### ISSUE TITLE
Getting negative fret values 

### ISSUE THREAD

**Issue by pasan9** [marl/GuitarSet#2]
Some excerpts have invalid note values that result in negative fret values!

**Comment by tomxi** [comment]
Thanks for reporting this! And sorry it took forever for me to get back to you. I had some health-related issues the past year.

I went back and looked at GuitarSet and indeed some excerpts have negative fret values. I've updated the set with this [script here](https://github.com/marl/GuitarSet/blob/master/patch/Clean_annotations_1_0_1.ipynb). The newly updated dataset is now available [here](https://zenodo.org/record/3371780).

Of course, since these changes are made without involving the original annotator, the steps performed by the script is really "curating" the existing annotations. Or in other words, post-processing.

In general, it's really hard to have a perfectly clean dataset; and despite our best efforts, there are some errors in the annotation for GuitarSet introduced by our annotators and our process. Sorry for the trouble it caused and hope you still find GuitarSet helpful.

I'll close this issue for now. Feel free to reopen.
